"""
Column metadata schema.

This schema describes the structure of the dynamic column metadata
returned by GET /api/v1/metadata. The frontend uses this to build
column selectors, filter panels, and indicator cards dynamically.
"""

from pydantic import BaseModel, Field
from typing import Optional


class ColumnMetadata(BaseModel):
    """
    Metadata describing a single DataFrame column.

    Generated by introspecting the live DataFrame's dtypes and column names.
    Can be overridden via column_overrides.json for display names/descriptions.
    """
    column: str = Field(..., description="Raw column name in DataFrame")
    display_name: str = Field(..., description="Human-readable display name")
    type: str = Field(..., description="Data type: number, string, datetime, boolean")
    unit: str = Field("", description="Display unit: ₹, %, etc.")
    description: str = Field("", description="Column description/tooltip")
    group: str = Field("Other", description="Grouping category: Price, Volume, Indicator, etc.")
    sortable: bool = Field(True, description="Whether this column can be sorted")
    filterable: bool = Field(True, description="Whether this column can be filtered")
    filter_type: str = Field(
        "text",
        description="Filter UI type: range, select, search, checkbox, date_range"
    )
    visible_default: bool = Field(False, description="Whether visible by default")
    operators: list[str] = Field(
        default_factory=lambda: [">", "<", ">=", "<=", "=", "!="],
        description="Supported filter/scanner operators"
    )


class MetadataResponse(BaseModel):
    """Response from GET /api/v1/metadata."""
    columns: list[ColumnMetadata]
    groups: list[str] = Field(
        default_factory=list,
        description="Ordered list of column group names"
    )
